backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"
search: false
editor:
  preview: false

collections:
  - name: "site"
    label: "Site Settings"
    description: >
        Edit design variables used for styling the UI.
    files:
      - file: "public/site-config.json"
        label: "Site Configuration"
        name: "site-config"
        fields:
          - { label: "Site Title", name: "title", widget: "string", required: true }
          - { label: "Site Description", name: "description", widget: "text", required: false }
          - { label: "Tagline", name: "tagline", widget: "text", required: false }
          - { label: "Favorites Description", name: "favorites-description", widget: "text", required: false }
          - { label: "Accent Color", name: "accent-color", widget: "color", required: false }
          - { label: "Genre Badge Color", name: "genre-badge-color", widget: "color", required: false }
          - { label: "Instrument Badge Color", name: "instrument-badge-color", widget: "color", required: false }
          - { label: "Tag Badge Color", name: "tag-badge-color", widget: "color", required: false }

  - name: "pdfs"
    label: "PDFs"
    label_singular: "Pdf"
    folder: "content/pdfs"
    description: >
      Collection of sheet music, tablature, or any PDf files to be displayed.
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Favorite', name: 'favorite', widget: 'boolean', default: false }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Artists", name: "artists", widget: "list", required: false }
      - { label: "Instruments", name: "instruments", widget: "list", required: false  }
      - { label: "Genres", name: "genres", widget: "list", required: false  }
      - { label: "Description", name: "description", widget: "text", required: false  }
      - { label: "PDF File", name: "file", widget: "file", media_library: { config: { multiple: false } }, required: true  }
      - { label: "Tags", name: "tags", widget: "list", required: false  }
